export const demoChannels = [
  {
    id: 'tokyo-shibuya',
    city: 'Tokyo',
    country: 'Japan',
    place: 'Shibuya Crossing',
    type: 'city',
    timezone: 'Asia/Tokyo',
    provider: 'windy',
    image_url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=1600&auto=format&fit=crop',
    source_url: 'https://www.windy.com/',
  },
  {
    id: 'santiago-alameda',
    city: 'Santiago',
    country: 'Chile',
    place: 'Alameda Centro',
    type: 'traffic',
    timezone: 'America/Santiago',
    provider: 'traffic',
    image_url: 'https://images.unsplash.com/photo-1519302959554-a75be0afc82a?q=80&w=1600&auto=format&fit=crop',
    source_url: 'https://www.transporteinforma.cl/',
  },
  {
    id: 'madrid-granvia',
    city: 'Madrid',
    country: 'Spain',
    place: 'Gran Vía / Callao',
    type: 'city',
    timezone: 'Europe/Madrid',
    provider: 'public',
    image_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=1600&auto=format&fit=crop',
    source_url: 'https://www.windy.com/',
  },
]
